import FWCore.ParameterSet.Config as cms

XMLIdealGeometryESSource = cms.ESSource("XMLIdealGeometryESSource",
    geomXMLFiles = cms.vstring(
        'Geometry/CMSCommonData/data/materials.xml',
        'Geometry/CMSCommonData/data/rotations.xml',
        #'Geometry/CMSCommonData/data/extend/v2/cmsextent.xml',
		'Geometry/FbcmCommonData/test/cmsextent.xml',
        'Geometry/CMSCommonData/data/cmsMother.xml',
#        'Geometry/CMSCommonData/data/eta3/etaMax.xml',
        'Geometry/CMSCommonData/data/cmsTracker.xml',
#        'Geometry/CMSCommonData/data/cmsCalo.xml',
#        'Geometry/CMSCommonData/data/cmsMuon.xml',
#        'Geometry/CMSCommonData/data/mgnt.xml',
#       'Geometry/CMSCommonData/data/beampipe/2026/v1/beampipe.xml',
#        'Geometry/CMSCommonData/data/cmsBeam/2026/v1/cmsBeam.xml',
#        'Geometry/CMSCommonData/data/muonMB.xml',
#        'Geometry/CMSCommonData/data/muonMagnet.xml',
#        'Geometry/CMSCommonData/data/cavern/2021/v1/cavern.xml',
        'Geometry/CMSCommonData/data/cavernData/2021/v1/cavernData.xml',
#        'Geometry/CMSCommonData/data/cavernFloor/2017/v1/cavernFloor.xml',
        'Geometry/CMSCommonData/data/cms/2026/v3/cms.xml',
#        'Geometry/CMSCommonData/data/caloBase/2026/v2/caloBase.xml',
#        'Geometry/CMSCommonData/data/muonBase/2026/v3/muonBase.xml',
        'Geometry/TrackerCommonData/data/PhaseII/trackerParameters.xml',
		'Geometry/FbcmCommonData/data/PhaseII/FbcmVolume/cmsFbcm.xml',
		'Geometry/FbcmCommonData/data/PhaseII/MultiSize_MultiRadius/v1/fbcm.xml',
		'Geometry/FbcmCommonData/data/PhaseII/MultiSize_MultiRadius/v1/FbcmSpecs.xml',
		'Geometry/FbcmSimData/data/PhaseII/FbcmSens.xml',
        'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
        'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker613_MB_2019_04/pixfwd.xml',
        'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker613_MB_2019_04/pixbar.xml',
        'Geometry/TrackerCommonData/data/trackermaterial.xml',
#        'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/otst.xml',
        'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker613_MB_2019_04/tracker.xml',
        'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker613_MB_2019_04/pixel.xml',
#        'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerbar.xml',
        'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerfwd.xml',
#        'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker404/trackerStructureTopology.xml',
#        'Geometry/TrackerCommonData/data/PhaseII/TiltedTracker613/pixelStructureTopology.xml',
#       'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/trackersens.xml',
#        'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/pixelsens.xml',
        'Geometry/TrackerRecoData/data/PhaseII/TiltedTracker613_MB_2019_04/trackerRecoMaterial.xml',
#        'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/trackerProdCuts.xml',
#        'Geometry/TrackerSimData/data/PhaseII/TiltedTracker404/pixelProdCuts.xml',
#        'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
    ),
    rootNodeName = cms.string('cms:OCMS')
)

